# Project information
site_name: COMSATS Course Outline
site_author: Nauman Umer
site_url: https://nmanumr.github.io/comsats-course-catalog
docs_dir: src
site_dir: docs

# Repository
repo_name: nmanumr/comsats-course-catalog
repo_url: https://github.com/nmanumr/comsats-course-catalog
edit_uri: ""

# Theme
theme:
  name: null
  disqus: 'comsats-course-catalog'
  language: 'en'
  custom_dir: theme/arc
  logo:
    icon: "\uE80C"
  feature:
    tabs: true

google_analytics:
  - UA-69868707-5
  - auto

nav:
  - Programs:
    - Index: "index.md"
    - BS Media Studies: "programs/bsms.md"
    - BS Computer Science: "programs/bcs.md"
    - BS Software Engineering: "programs/bse.md"
    - BS Computer Engineering: "programs/bce.md"
    - BS Chemical Engineering: "programs/che.md"
    - BS Electrical Engineering: "programs/bee.md"
    - BS Business Administration: "programs/bba.md"
    - BS Accounting & Finance: "programs/baf.md"
    - BS Economics: "programs/bec.md"
    - BS Physics: "programs/bph.md"
    - BS Psychology: "programs/bpy.md"
    - BS Mathematics: "programs/bsm.md"
    - BS Statistics: "programs/bss.md"
    - B Design: "programs/bde.md"
    - B Interior Design: "programs/bid.md"
    - B Architecture: "programs/bar.md"
    - _Courses:
      - Index: "courses/index.md"
      - CSC101: "courses/CSC101.md"
      - CSC102: "courses/CSC102.md"
      - CSC102: "courses/CSC103.md"
      - CSC110: "courses/CSC110.md"
      - HUM100: "courses/HUM100.md"
      - HUM102: "courses/HUM102.md"
      - HUM110: "courses/HUM110.md"
      - MTH104: "courses/MTH104.md"
      - MTH105: "courses/MTH105.md"
      - PHY121: "courses/PHY121.md"


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
    - assets/styles/utils.css

plugins:
  - search
  - auto-course-plugin